SELECT * FROM BOOKS_CATEGORIES;
SELECT * FROM BOOKS;
SELECT * FROM BOOKS_AUTHORS;
SELECT * FROM CUSTOMERS;
SELECT * FROM CUSTOMERS_ORDERS;
SELECT * FROM ORDER_CONTENT;

SELECT * FROM BOOKS WHERE name LIKE 'Пр%';
SELECT * FROM BOOKS WHERE category IN (4,5,7);
SELECT * FROM BOOKS WHERE price BETWEEN 300 AND 400;

SELECT max(items) FROM BOOKS;

SELECT * FROM BOOKS ORDER BY category, name;

SELECT category, COUNT(name) FROM BOOKS GROUP BY category HAVING COUNT(name)>1;

